include: package:flutter_lints/flutter.yaml

linter:
  rules:
    require_trailing_commas: true
    unnecessary_lambdas: true

analyzer:
  errors:
    deprecated_member_use: true
    deprecated_member_use_from_same_package: false
    use_build_context_synchronously: ignore

  exclude: [
    lib/**.g.dart
  ]
